/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 12 07:55:12 CET 2015
 */

package sbes.distance;

import static org.junit.Assert.assertEquals;

import org.junit.Test;
 
public class DistanceTest {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I174 Branch 18 IFNULL L107 - true
   */

  @Test
  public void test0()  throws Throwable  {
      Object object0 = new Object();
      DistancePair distancePair0 = new DistancePair(object0, object0);
      Object object1 = new Object();
      DistancePair distancePair1 = new DistancePair(object1, object1);
      double double0 = Distance.distance((Object) distancePair1, (Object) distancePair0);
      assertEquals(0.0, double0, 0.01D);
  }

  //Test case number: 1
  /*
   * 3 covered goals:
   * 1 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I130 Branch 15 IFEQ L95 - false
   * 2 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I168 Branch 17 IFNULL L107 - false
   * 3 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I174 Branch 18 IFNULL L107 - false
   */

  @Test
  public void test1()  throws Throwable  {
      DistancePair distancePair0 = new DistancePair((Object) "#i:c<!{*He3YI", (Object) "#i:c<!{*He3YI");
      distancePair0.o2 = (Object) distancePair0;
      double double0 = Distance.distance(distancePair0.o2, (Object) distancePair0);
      assertEquals(0.0, double0, 0.01D);
  }

  //Test case number: 2
  /*
   * 1 covered goal:
   * 1 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I114 Branch 14 IFEQ L89 - false
   */

  @Test
  public void test2()  throws Throwable  {
      double double0 = Distance.distance((Object) 0.0, (Object) 0.0);
      assertEquals(0.0, double0, 0.01D);
  }

  //Test case number: 3
  /*
   * 2 covered goals:
   * 1 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I43 Branch 9 IFNONNULL L71 - false
   * 2 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I57 Branch 11 IFNONNULL L74 - false
   */

  @Test
  public void test3()  throws Throwable  {
      Integer integer0 = new Integer(1);
      DistancePair distancePair0 = new DistancePair((Object) null, (Object) integer0);
      DistancePair distancePair1 = new DistancePair((Object) null, (Object) null);
      double double0 = Distance.distance((Object) distancePair0, (Object) distancePair1);
      assertEquals(1000000.0, double0, 0.01D);
  }

  //Test case number: 4
  /*
   * 22 covered goals:
   * 1 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I41 Branch 8 IFNONNULL L71 - false
   * 2 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I43 Branch 9 IFNONNULL L71 - true
   * 3 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I50 Branch 10 IFNONNULL L74 - false
   * 4 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I64 Branch 12 IFEQ L74 - false
   * 5 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I83 Branch 13 IFNE L80 - true
   * 6 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I114 Branch 14 IFEQ L89 - true
   * 7 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I130 Branch 15 IFEQ L95 - true
   * 8 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I149 Branch 16 IFEQ L101 - true
   * 9 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I168 Branch 17 IFNULL L107 - true
   * 10 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I224 Branch 19 IFEQ L123 - true
   * 11 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I258 Branch 21 IFNE L127 - false
   * 12 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I261 Branch 22 IFEQ L127 - true
   * 13 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I304 Branch 23 TABLESWITCH L133 Case 1 - false
   * 14 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I304 Branch 24 TABLESWITCH L133 Case 2 - false
   * 15 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I304 Branch 25 TABLESWITCH L133 Case 3 - false
   * 16 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I304 Branch 26 TABLESWITCH L133 Case 4 - true
   * 17 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I304 Branch 27 TABLESWITCH L133 Default-Case - false
   * 18 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I403 Branch 28 IF_ICMPLT L114 - true
   * 19 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I403 Branch 28 IF_ICMPLT L114 - false
   * 20 sbes.distance.Distance.getComparisonType(Ljava/lang/Class;Ljava/lang/Class;)Lsbes/distance/ComparisonType;: I4 Branch 64 IFEQ L357 - true
   * 21 sbes.distance.Distance.getComparisonType(Ljava/lang/Class;Ljava/lang/Class;)Lsbes/distance/ComparisonType;: I13 Branch 65 IFEQ L360 - true
   * 22 sbes.distance.Distance.getComparisonType(Ljava/lang/Class;Ljava/lang/Class;)Lsbes/distance/ComparisonType;: I23 Branch 66 IFEQ L363 - true
   */

  @Test
  public void test4()  throws Throwable  {
      DistancePair distancePair0 = new DistancePair((Object) null, (Object) null);
      DistancePair distancePair1 = new DistancePair((Object) ";qPDZInrSn", (Object) ";qPDZInrSn");
      double double0 = Distance.distance((Object) distancePair0, (Object) distancePair1);
      assertEquals(2000000.0, double0, 0.01D);
  }

  //Test case number: 5
  /*
   * 1 covered goal:
   * 1 sbes.distance.Distance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I40 Branch 4 IFNONNULL L34 - false
   */

  @Test
  public void test5()  throws Throwable  {
      Object object0 = new Object();
      double double0 = Distance.distance(object0, (Object) null);
      assertEquals(1000000.0, double0, 0.01D);
  }

  //Test case number: 6
  /*
   * 3 covered goals:
   * 1 sbes.distance.Distance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I20 Branch 2 IFNONNULL L30 - true
   * 2 sbes.distance.Distance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I33 Branch 3 IFNONNULL L34 - false
   * 3 sbes.distance.Distance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I47 Branch 5 IFEQ L34 - false
   */

  @Test
  public void test6()  throws Throwable  {
      Integer integer0 = new Integer(1);
      double double0 = Distance.distance((Object) null, (Object) integer0);
      assertEquals(1000000.0, double0, 0.01D);
  }

  //Test case number: 7
  /*
   * 2 covered goals:
   * 1 sbes.distance.Distance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I18 Branch 1 IFNONNULL L30 - false
   * 2 sbes.distance.Distance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I20 Branch 2 IFNONNULL L30 - false
   */

  @Test
  public void test7()  throws Throwable  {
      double double0 = Distance.distance((Object) null, (Object) null);
      assertEquals(0.0, double0, 0.01D);
  }

  //Test case number: 8
  /*
   * 16 covered goals:
   * 1 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I41 Branch 8 IFNONNULL L71 - true
   * 2 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I50 Branch 10 IFNONNULL L74 - true
   * 3 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I57 Branch 11 IFNONNULL L74 - true
   * 4 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I64 Branch 12 IFEQ L74 - true
   * 5 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I83 Branch 13 IFNE L80 - false
   * 6 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I408 Branch 29 IFLE L64 - true
   * 7 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I408 Branch 29 IFLE L64 - false
   * 8 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I414 Branch 30 IFEQ L64 - true
   * 9 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I414 Branch 30 IFEQ L64 - false
   * 10 sbes.distance.Distance.calculate(Ljava/lang/Object;Ljava/lang/Object;)D: I418 Branch 31 IFLE L164 - true
   * 11 sbes.distance.Distance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I18 Branch 1 IFNONNULL L30 - true
   * 12 sbes.distance.Distance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I33 Branch 3 IFNONNULL L34 - true
   * 13 sbes.distance.Distance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I40 Branch 4 IFNONNULL L34 - true
   * 14 sbes.distance.Distance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I47 Branch 5 IFEQ L34 - true
   * 15 sbes.distance.Distance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I76 Branch 6 IFNE L42 - true
   * 16 sbes.distance.Distance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I95 Branch 7 IFEQ L47 - true
   */

  @Test
  public void test8()  throws Throwable  {
      DistancePair distancePair0 = new DistancePair((Object) "#i:c<!{*He3YI", (Object) "#i:c<!{*He3YI");
      double double0 = Distance.distance(distancePair0.o2, (Object) distancePair0);
      assertEquals(1000.0, double0, 0.01D);
  }
}
