/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 12 08:00:25 CET 2015
 */

package sbes.distance;

import static org.junit.Assert.assertEquals;

import org.junit.Test;
 
public class ObjectDistanceTest {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 sbes.distance.ObjectDistance.getNullDistance(Ljava/lang/Object;Ljava/lang/Object;)D: I35 Branch 4 IFEQ L22 - false
   */

  @Test
  public void test0()  throws Throwable  {
      ObjectDistance objectDistance0 = new ObjectDistance();
      Integer integer0 = new Integer((-14));
      double double0 = ObjectDistance.getNullDistance((Object) integer0, (Object) objectDistance0);
      assertEquals(1000000.0, double0, 0.01D);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 sbes.distance.ObjectDistance.getNullDistance(Ljava/lang/Object;Ljava/lang/Object;)D: I8 Branch 2 IFEQ L13 - false
   */

  @Test
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer((-14));
      double double0 = ObjectDistance.getNullDistance((Object) null, (Object) integer0);
      assertEquals(1000000.0, double0, 0.01D);
  }

  //Test case number: 2
  /*
   * 9 covered goals:
   * 1 sbes.distance.ObjectDistance.getNullDistance(Ljava/lang/Object;Ljava/lang/Object;)D: I3 Branch 1 IFNONNULL L12 - false
   * 2 sbes.distance.ObjectDistance.getNullDistance(Ljava/lang/Object;Ljava/lang/Object;)D: I8 Branch 2 IFEQ L13 - true
   * 3 sbes.distance.ObjectDistance.getNullDistance(Ljava/lang/Object;Ljava/lang/Object;)D: I21 Branch 3 IFLE L18 - true
   * 4 sbes.distance.ObjectDistance.getObjectSize(Ljava/lang/Object;)I: I66 Branch 6 IFNE L44 - false
   * 5 sbes.distance.ObjectDistance.getObjectSize(Ljava/lang/Object;)I: I70 Branch 7 IFLE L44 - true
   * 6 sbes.distance.ObjectDistance.getObjectSize(Ljava/lang/Object;)I: I70 Branch 7 IFLE L44 - false
   * 7 sbes.distance.ObjectDistance.getObjectSize(Ljava/lang/Object;)I: I76 Branch 8 IFNE L44 - true
   * 8 sbes.distance.ObjectDistance.getObjectSize(Ljava/lang/Object;)I: I76 Branch 8 IFNE L44 - false
   * 9 sbes.distance.ObjectDistance.getObjectSize(Ljava/lang/Object;)I: I88 Branch 9 IFNE L41 - true
   */

  @Test
  public void test2()  throws Throwable  {
      double double0 = ObjectDistance.getNullDistance((Object) null, (Object) "sbes.utilXRefleti[nUtiP");
      assertEquals(1000000.0, double0, 0.01D);
  }

  //Test case number: 3
  /*
   * 9 covered goals:
   * 1 sbes.distance.ObjectDistance.<init>()V: root-Branch
   * 2 sbes.distance.ObjectDistance.getNullDistance(Ljava/lang/Object;Ljava/lang/Object;)D: I3 Branch 1 IFNONNULL L12 - true
   * 3 sbes.distance.ObjectDistance.getNullDistance(Ljava/lang/Object;Ljava/lang/Object;)D: I35 Branch 4 IFEQ L22 - true
   * 4 sbes.distance.ObjectDistance.getNullDistance(Ljava/lang/Object;Ljava/lang/Object;)D: I48 Branch 5 IFLE L27 - true
   * 5 sbes.distance.ObjectDistance.getObjectSize(Ljava/lang/Object;)I: I88 Branch 9 IFNE L41 - false
   * 6 sbes.distance.ObjectDistance.getObjectSize(Ljava/lang/Object;)I: I93 Branch 10 IFLE L37 - true
   * 7 sbes.distance.ObjectDistance.getObjectSize(Ljava/lang/Object;)I: I93 Branch 10 IFLE L37 - false
   * 8 sbes.distance.ObjectDistance.getObjectSize(Ljava/lang/Object;)I: I99 Branch 11 IFEQ L37 - true
   * 9 sbes.distance.ObjectDistance.getObjectSize(Ljava/lang/Object;)I: I99 Branch 11 IFEQ L37 - false
   */

  @Test
  public void test3()  throws Throwable  {
      ObjectDistance objectDistance0 = new ObjectDistance();
      double double0 = ObjectDistance.getNullDistance((Object) objectDistance0, (Object) null);
      assertEquals(1000000.0, double0, 0.01D);
  }
}
