/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 12 07:58:30 CET 2015
 */

package sbes.distance;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.junit.Test;
 
public class PrimitiveDistanceTest {

  //Test case number: 0
  /*
   * 5 covered goals:
   * 1 sbes.distance.PrimitiveDistance.booleanDistance([Z[Z)D: I32 Branch 68 IF_ICMPLT L290 - true
   * 2 sbes.distance.PrimitiveDistance.booleanDistance([Z[Z)D: I32 Branch 68 IF_ICMPLT L290 - false
   * 3 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I378 Branch 37 IFNE L137 - true
   * 4 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I388 Branch 39 IFEQ L138 - false
   * 5 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I394 Branch 40 IFEQ L139 - true
   */

  @Test
  public void test00()  throws Throwable  {
      boolean[] booleanArray0 = new boolean[7];
      double double0 = PrimitiveDistance.distance((Object) booleanArray0, (Object) booleanArray0);
      assertEquals(0.0, double0, 0.01D);
  }

  //Test case number: 1
  /*
   * 1 covered goal:
   * 1 sbes.distance.PrimitiveDistance.booleanDistance(ZZ)D: I5 Branch 67 IFEQ L285 - false
   */

  @Test
  public void test01()  throws Throwable  {
      double double0 = PrimitiveDistance.booleanDistance(false, true);
      assertEquals(1.0, double0, 0.01D);
  }

  //Test case number: 2
  /*
   * 2 covered goals:
   * 1 sbes.distance.PrimitiveDistance.shortDistance([S[S)D: I32 Branch 46 IF_ICMPLT L189 - true
   * 2 sbes.distance.PrimitiveDistance.shortDistance([S[S)D: I32 Branch 46 IF_ICMPLT L189 - false
   */

  @Test
  public void test02()  throws Throwable  {
      short[] shortArray0 = new short[3];
      double double0 = PrimitiveDistance.shortDistance(shortArray0, shortArray0);
      assertEquals(0.0, double0, 0.01D);
  }

  //Test case number: 3
  /*
   * 1 covered goal:
   * 1 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I441 Branch 42 IFEQ L150 - true
   */

  @Test
  public void test03()  throws Throwable  {
      Object object0 = new Object();
      Character character0 = new Character('k');
      double double0 = PrimitiveDistance.distance(object0, (Object) character0);
      assertEquals(0.0, double0, 0.01D);
  }

  //Test case number: 4
  /*
   * 3 covered goals:
   * 1 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I437 Branch 41 IFNE L150 - false
   * 2 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I441 Branch 42 IFEQ L150 - false
   * 3 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I447 Branch 43 IFEQ L151 - true
   */

  @Test
  public void test04()  throws Throwable  {
      double double0 = PrimitiveDistance.distance((Object) (byte)0, (Object) (byte)0);
      assertEquals(0.0, double0, 0.01D);
  }

  //Test case number: 5
  /*
   * 3 covered goals:
   * 1 sbes.distance.PrimitiveDistance.booleanDistance(ZZ)D: I5 Branch 67 IFEQ L285 - true
   * 2 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I382 Branch 38 IFEQ L137 - false
   * 3 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I388 Branch 39 IFEQ L138 - true
   */

  @Test
  public void test05()  throws Throwable  {
      Boolean boolean0 = Boolean.valueOf(true);
      double double0 = PrimitiveDistance.distance((Object) boolean0, (Object) boolean0);
      assertEquals(0.0, double0, 0.01D);
  }

  //Test case number: 6
  /*
   * 2 covered goals:
   * 1 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I323 Branch 34 IFEQ L124 - false
   * 2 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I329 Branch 35 IFEQ L125 - true
   */

  @Test
  public void test06()  throws Throwable  {
      Object object0 = new Object();
      // Undeclared exception!
      try {
        PrimitiveDistance.distance((Object) 0.0, object0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Object cannot be cast to java.lang.Double
         //
      }
  }

  //Test case number: 7
  /*
   * 11 covered goals:
   * 1 sbes.distance.PrimitiveDistance.doubleDistance(DD)D: I4 Branch 57 IFEQ L235 - true
   * 2 sbes.distance.PrimitiveDistance.doubleDistance(DD)D: I16 Branch 59 IFNE L238 - false
   * 3 sbes.distance.PrimitiveDistance.doubleDistance(DD)D: I19 Branch 60 IFEQ L238 - true
   * 4 sbes.distance.PrimitiveDistance.doubleDistance(DD)D: I28 Branch 61 IFEQ L241 - true
   * 5 sbes.distance.PrimitiveDistance.doubleDistance(DD)D: I40 Branch 63 IFNE L244 - false
   * 6 sbes.distance.PrimitiveDistance.doubleDistance(DD)D: I43 Branch 64 IFEQ L244 - true
   * 7 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I319 Branch 33 IFNE L124 - true
   * 8 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I329 Branch 35 IFEQ L125 - false
   * 9 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I335 Branch 36 IFEQ L126 - true
   * 10 sbes.distance.PrimitiveDistance.doubleDistance([D[D)D: I32 Branch 65 IF_ICMPLT L252 - true
   * 11 sbes.distance.PrimitiveDistance.doubleDistance([D[D)D: I32 Branch 65 IF_ICMPLT L252 - false
   */

  @Test
  public void test07()  throws Throwable  {
      double[] doubleArray0 = new double[4];
      double double0 = PrimitiveDistance.distance((Object) doubleArray0, (Object) doubleArray0);
      assertEquals(0.0, double0, 0.01D);
  }

  //Test case number: 8
  /*
   * 2 covered goals:
   * 1 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I264 Branch 30 IFEQ L111 - false
   * 2 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I270 Branch 31 IFEQ L112 - true
   */

  @Test
  public void test08()  throws Throwable  {
      Short short0 = new Short((short) (-2718));
      Float float0 = new Float((double) (short) (-2718));
      // Undeclared exception!
      try {
        PrimitiveDistance.distance((Object) float0, (Object) short0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Short cannot be cast to java.lang.Float
         //
      }
  }

  //Test case number: 9
  /*
   * 11 covered goals:
   * 1 sbes.distance.PrimitiveDistance.floatDistance(FF)D: I4 Branch 48 IFEQ L210 - true
   * 2 sbes.distance.PrimitiveDistance.floatDistance(FF)D: I16 Branch 50 IFNE L213 - false
   * 3 sbes.distance.PrimitiveDistance.floatDistance(FF)D: I19 Branch 51 IFEQ L213 - true
   * 4 sbes.distance.PrimitiveDistance.floatDistance(FF)D: I28 Branch 52 IFEQ L216 - true
   * 5 sbes.distance.PrimitiveDistance.floatDistance(FF)D: I40 Branch 54 IFNE L219 - false
   * 6 sbes.distance.PrimitiveDistance.floatDistance(FF)D: I43 Branch 55 IFEQ L219 - true
   * 7 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I260 Branch 29 IFNE L111 - true
   * 8 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I270 Branch 31 IFEQ L112 - false
   * 9 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I276 Branch 32 IFEQ L113 - true
   * 10 sbes.distance.PrimitiveDistance.floatDistance([F[F)D: I32 Branch 56 IF_ICMPLT L227 - true
   * 11 sbes.distance.PrimitiveDistance.floatDistance([F[F)D: I32 Branch 56 IF_ICMPLT L227 - false
   */

  @Test
  public void test09()  throws Throwable  {
      float[] floatArray0 = new float[5];
      double double0 = PrimitiveDistance.distance((Object) floatArray0, (Object) floatArray0);
      assertEquals(0.0, double0, 0.01D);
  }

  //Test case number: 10
  /*
   * 2 covered goals:
   * 1 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I205 Branch 26 IFEQ L98 - false
   * 2 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I211 Branch 27 IFEQ L99 - true
   */

  @Test
  public void test10()  throws Throwable  {
      Long long0 = new Long((long) (short)448);
      double double0 = PrimitiveDistance.distance((Object) long0, (Object) long0);
      assertEquals(0.0, double0, 0.01D);
  }

  //Test case number: 11
  /*
   * 6 covered goals:
   * 1 sbes.distance.PrimitiveDistance.longDistance(JJ)D: root-Branch
   * 2 sbes.distance.PrimitiveDistance.longDistance([J[J)D: I32 Branch 47 IF_ICMPLT L202 - true
   * 3 sbes.distance.PrimitiveDistance.longDistance([J[J)D: I32 Branch 47 IF_ICMPLT L202 - false
   * 4 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I201 Branch 25 IFNE L98 - true
   * 5 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I211 Branch 27 IFEQ L99 - false
   * 6 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I217 Branch 28 IFEQ L100 - true
   */

  @Test
  public void test11()  throws Throwable  {
      long[] longArray0 = new long[16];
      double double0 = PrimitiveDistance.distance((Object) longArray0, (Object) longArray0);
      assertEquals(0.0, double0, 0.01D);
  }

  //Test case number: 12
  /*
   * 3 covered goals:
   * 1 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I142 Branch 21 IFNE L85 - true
   * 2 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I152 Branch 23 IFEQ L86 - false
   * 3 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I158 Branch 24 IFEQ L87 - true
   */

  @Test
  public void test12()  throws Throwable  {
      Boolean boolean0 = Boolean.valueOf(true);
      short[] shortArray0 = new short[19];
      // Undeclared exception!
      try {
        PrimitiveDistance.distance((Object) shortArray0, (Object) boolean0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Boolean cannot be cast to [S
         //
      }
  }

  //Test case number: 13
  /*
   * 2 covered goals:
   * 1 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I87 Branch 18 IFEQ L72 - false
   * 2 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I93 Branch 19 IFEQ L73 - true
   */

  @Test
  public void test13()  throws Throwable  {
      Character character0 = new Character('Z');
      Object object0 = new Object();
      // Undeclared exception!
      try {
        PrimitiveDistance.distance((Object) character0, object0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Object cannot be cast to java.lang.Character
         //
      }
  }

  //Test case number: 14
  /*
   * 2 covered goals:
   * 1 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I28 Branch 14 IFEQ L59 - false
   * 2 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I34 Branch 15 IFEQ L60 - true
   */

  @Test
  public void test14()  throws Throwable  {
      double[] doubleArray0 = new double[4];
      Integer integer0 = new Integer(0);
      // Undeclared exception!
      try {
        PrimitiveDistance.distance((Object) integer0, (Object) doubleArray0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // [D cannot be cast to java.lang.Integer
         //
      }
  }

  //Test case number: 16
  /*
   * 6 covered goals:
   * 1 sbes.distance.PrimitiveDistance.intDistance(II)D: root-Branch
   * 2 sbes.distance.PrimitiveDistance.intDistance([I[I)D: I32 Branch 45 IF_ICMPLT L176 - true
   * 3 sbes.distance.PrimitiveDistance.intDistance([I[I)D: I32 Branch 45 IF_ICMPLT L176 - false
   * 4 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I24 Branch 13 IFNE L59 - true
   * 5 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I34 Branch 15 IFEQ L60 - false
   * 6 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I40 Branch 16 IFEQ L61 - true
   */

  @Test
  public void test16()  throws Throwable  {
      int[] intArray0 = new int[1];
      double double0 = PrimitiveDistance.distance((Object) intArray0, (Object) intArray0);
      assertEquals(0.0, double0, 0.01D);
  }

  //Test case number: 17
  /*
   * 15 covered goals:
   * 1 sbes.distance.PrimitiveDistance.byteDistance(BB)D: root-Branch
   * 2 sbes.distance.PrimitiveDistance.byteDistance([B[B)D: I32 Branch 66 IF_ICMPLT L265 - true
   * 3 sbes.distance.PrimitiveDistance.byteDistance([B[B)D: I32 Branch 66 IF_ICMPLT L265 - false
   * 4 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I146 Branch 22 IFEQ L85 - true
   * 5 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I201 Branch 25 IFNE L98 - false
   * 6 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I205 Branch 26 IFEQ L98 - true
   * 7 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I260 Branch 29 IFNE L111 - false
   * 8 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I264 Branch 30 IFEQ L111 - true
   * 9 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I319 Branch 33 IFNE L124 - false
   * 10 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I323 Branch 34 IFEQ L124 - true
   * 11 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I378 Branch 37 IFNE L137 - false
   * 12 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I382 Branch 38 IFEQ L137 - true
   * 13 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I437 Branch 41 IFNE L150 - true
   * 14 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I447 Branch 43 IFEQ L151 - false
   * 15 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I453 Branch 44 IFEQ L152 - true
   */

  @Test
  public void test17()  throws Throwable  {
      byte[] byteArray0 = new byte[6];
      double double0 = PrimitiveDistance.distance((Object) byteArray0, (Object) byteArray0);
      assertEquals(0.0, double0, 0.01D);
  }

  //Test case number: 18
  /*
   * 7 covered goals:
   * 1 sbes.distance.PrimitiveDistance.shortDistance(SS)D: root-Branch
   * 2 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I9 Branch 12 IFNONNULL L57 - false
   * 3 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I83 Branch 17 IFNE L72 - false
   * 4 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I87 Branch 18 IFEQ L72 - true
   * 5 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I142 Branch 21 IFNE L85 - false
   * 6 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I146 Branch 22 IFEQ L85 - false
   * 7 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I152 Branch 23 IFEQ L86 - true
   */

  @Test
  public void test18()  throws Throwable  {
      Short short0 = new Short((short)1262);
      double double0 = PrimitiveDistance.distance((Object) short0, (Object) short0);
      assertEquals(0.0, double0, 0.01D);
  }

  //Test case number: 19
  /*
   * 7 covered goals:
   * 1 sbes.distance.PrimitiveDistance.charDistance([C[C)D: root-Branch
   * 2 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I9 Branch 12 IFNONNULL L57 - true
   * 3 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I24 Branch 13 IFNE L59 - false
   * 4 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I28 Branch 14 IFEQ L59 - true
   * 5 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I83 Branch 17 IFNE L72 - true
   * 6 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I93 Branch 19 IFEQ L73 - false
   * 7 sbes.distance.PrimitiveDistance.distance(Ljava/lang/Object;Ljava/lang/Object;)D: I99 Branch 20 IFEQ L74 - true
   */

  @Test
  public void test19()  throws Throwable  {
      char[] charArray0 = new char[5];
      double double0 = PrimitiveDistance.distance((Object) charArray0, (Object) charArray0);
      assertEquals(0.0, double0, 0.01D);
  }

  //Test case number: 20
  /*
   * 1 covered goal:
   * 1 sbes.distance.PrimitiveDistance.charDistance(CC)D: root-Branch
   */

  @Test
  public void test20()  throws Throwable  {
      double double0 = PrimitiveDistance.charDistance('k', 'k');
      assertEquals(0.0, double0, 0.01D);
  }
}
