/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 11 20:42:25 CET 2015
 */

package sbes.scenario;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertSame;

import java.util.LinkedList;
import java.util.List;

import org.junit.Test;

public class TestScenarioRepositoryTest {

	//Test case number: 0
	/*
	 * 1 covered goal:
	 * 1 sbes.scenario.TestScenarioRepository.I()Lsbes/scenario/TestScenarioRepository;: I3 Branch 1 IFNONNULL L19 - true
	 */

	@Test
	public void test0()  throws Throwable  {
		TestScenarioRepository testScenarioRepository0 = TestScenarioRepository.I();
		TestScenarioRepository testScenarioRepository1 = TestScenarioRepository.I();
		assertSame(testScenarioRepository1, testScenarioRepository0);
	}

	//Test case number: 1
	/*
	 * 1 covered goal:
	 * 1 sbes.scenario.TestScenarioRepository.getScenarios()Ljava/util/List;: root-Branch
	 */

	@Test
	public void test1()  throws Throwable  {
		TestScenarioRepository testScenarioRepository0 = TestScenarioRepository.I();
		List<TestScenario> list0 = testScenarioRepository0.getScenarios();
		assertEquals(true, list0.isEmpty());
	}

	//Test case number: 2
	/*
	 * 1 covered goal:
	 * 1 sbes.scenario.TestScenarioRepository.addScenarios(Ljava/util/List;)V: root-Branch
	 */

	@Test
	public void test2()  throws Throwable  {
		TestScenarioRepository testScenarioRepository0 = TestScenarioRepository.I();
		LinkedList<TestScenario> linkedList0 = new LinkedList<TestScenario>();
		testScenarioRepository0.addScenarios((List<TestScenario>) linkedList0);
		assertEquals(true, testScenarioRepository0.getScenarios().isEmpty());
	}

	//Test case number: 3
	/*
	 * 1 covered goal:
	 * 1 sbes.scenario.TestScenarioRepository.addScenario(Lsbes/scenario/TestScenario;)V: root-Branch
	 */

	@Test
	public void test3()  throws Throwable  {
		TestScenarioRepository testScenarioRepository0 = TestScenarioRepository.I();
		testScenarioRepository0.addScenario((TestScenario) null);
		assertEquals(1, testScenarioRepository0.getScenarios().size());
	}

	//Test case number: 4
	/*
	 * 1 covered goal:
	 * 1 sbes.scenario.TestScenarioRepository.resetCounterexamples()V: root-Branch
	 */

	@Test
	public void test4()  throws Throwable  {
		TestScenarioRepository testScenarioRepository0 = TestScenarioRepository.I();
		assertEquals(0, testScenarioRepository0.getScenarios().size());
		testScenarioRepository0.addCounterexample(null);
		assertEquals(1, testScenarioRepository0.getScenarios().size());
		testScenarioRepository0.addScenario((TestScenario) null);
		assertEquals(2, testScenarioRepository0.getScenarios().size());
		testScenarioRepository0.resetCounterexamples();
		assertEquals(1, testScenarioRepository0.getScenarios().size());
	}

}
