/*
 * This file was automatically generated by EvoSuite
 */

package com.google.common.collect;

import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.junit.Test;

import com.google.common.collect.ArrayListMultimap;

public class StackEvoSuiteTest {

	@Test
	public void test0()  throws Throwable  {
		ArrayListMultimap<Integer, String> arrayListMultimap0 = ArrayListMultimap.create();
		Integer integer0 = new Integer(234);
		List<String> list0 = new ArrayList();
		list0.add("pippo");
		boolean boolean0 = arrayListMultimap0.putAll(integer0, list0);
		Integer integer3 = new Integer(-1698);
		String string0 = "pluto";
		boolean boolean3 = arrayListMultimap0.put(integer3, string0);
	}
	
	@Test
	public void test1()  throws Throwable  {
		ArrayListMultimap<Integer, String> arrayListMultimap0 = ArrayListMultimap.create();
		boolean boolean1 = arrayListMultimap0.put(-1698, "pluto");
		boolean boolean2 = arrayListMultimap0.put(123, "asd");
		boolean boolean3 = arrayListMultimap0.put(18, "ginger");
		boolean boolean4 = arrayListMultimap0.remove(18, "ginger");
	}
	
}
